download_data:
	yt-dlp https://www.youtube.com/watch?v=4i_GFrlaStQ -o "remember"
	yt-dlp https://www.youtube.com/watch?v=XLoGvZNG7o4 -o "2016-06-24 Krydset Sdr Boulevard Kløvermosevej.mp4"

clear:
	rm -f "2016-06-24 Krydset Sdr Boulevard Kløvermosevej.mp4"
	rm -f "remember.mkv"
